# Developer/devops role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
      - batch
      - apps
      - autoscaling
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - deployments
      - deployments/scale
      - endpoints
      - events
      - pods
      - pods/attach
      - pods/binding
      - pods/eviction
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - pods/status
      - podtemplates
      - secrets
      - serviceaccounts
      - services
      - services/proxy
      - services/status
      - ingresses
      - horizontalpodautoscalers
      
---
# developer /devops Cluster Role Binding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: default
