---
# XLD Cluster Role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xld
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - networking.k8s.io
  - extensions
  resources:
  - deployments
  - ingresses
  - services
  - services/proxy
  - services/status
  - pods
  - pods/attach
  - pods/binding
  - pods/eviction
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/proxy
  - pods/status
  - podtemplates
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
  - delete


---
# XLD Cluster Role Binding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xld
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xld
subjects:
- kind: ServiceAccount
  name: xld
  namespace: default
